GET http://localhost:4000/blog
###
POST http://localhost:5000/blog
content-type: application/json

{
    "title": "This is post 3",
    "author": "Puncharas",
    "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "content_img": [{"url":"https://cdn.pixabay.com/photo/2021/06/19/17/51/italy-6349105_960_720.jpg"}],
    "meta": {
        "votes": 1,
        "favs": 2
    }
}

###
PUT http://localhost:5000/blog/60fb9163b654a82a8cb4e84b
content-type: application/json

{
    "title": "This isDDDD Update",
    "author": "Puncharas",
    "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

### SignUp
POST http://localhost:4000/user/signup
content-type: application/json

{
    "name" : "Puncharas",
    "lastname" : "Phosap",
    "email" : "test@test.com",
    "password" : "123456"
}
### SignIn
POST http://localhost:4000/user/signin
content-type: application/json

{
    "email" : "test@test.com",
    "password" : "123456"
}
